### PR TITLE
added ability to rescope sub modules

### PR DESCRIPTION
**Pull request by mrlannigan**
also switched back to upstream rewrite-js

### CODE REVIEW

**Comment by soldair** [comment]
shoot. forgot to push the switch to upstream.
=) reviewing

**Comment by soldair** [comment]
im a maintainer on rewrite-js now so we dont have to bother chris so much =)

**Comment by soldair** [comment]
so what does this do? I thought you could scope or unscope anything any way you wanted already

**Comment by soldair** [comment]
oohhhhhh
this fixes
`require('@scope/module/lib/bananas')`

awesome!!!

**Comment by mrlannigan** [comment]
This allows for requires like this:

```
var something = require('some-module/dude');
```

to be rescoped to:

```
var something = require('@scope/some-module/dude');
```

**Comment by mrlannigan** [comment]
:+1:

**Comment by mrlannigan** [comment]
Also, I fixed rescoping in the package deps.

**Comment by soldair** [comment]
looks great.
if you are happy with it and tests out fine merge away :sheep:

we need tests with fixture modules asap because this is getting complicated =)
created #11

**Comment by soldair** [comment]
is this all done?

**Comment by mrlannigan** [comment]
Yea. Going to merge.

**Comment by soldair** [comment]
published as 1.1.0

**Pull request merged**
