### PR TITLE
Correct proc spawn opts

### PR DESCRIPTION
**Pull request by mrlannigan**

### CODE REVIEW

**Comment by soldair** [comment]
looks good thanks!

**Comment by soldair** [comment]
i dont see any reason why this should not be merged even if #7 is fixed right?

**Comment by soldair** [comment]
added you as a collaborator. thanks!
check out contributing guidelines etc in https://github.com/npm/scope-it/blob/master/CONTRIBUTING.md

**Comment by mrlannigan** [comment]
Thanks and I'm sure you already answered your question, but yea this is separate from #7.

**Pull request merged**
